name: Trigger Target Workflow

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      
      - name: install reproschema
        run: |
          pip install reproschema

      - name: Run tests
        run: |
          reproschema --version

      - name: Set up Git configuration
        run: |
          git rev-parse --abbrev-ref HEAD
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global credential.helper cache
          git clone --depth 1 https://${{ secrets.AUTH }}@github.com/Evan8456/bridge2ai-redcap

      - name: Get redcap csv
        run: |
          ls
          cd bridge2ai-redcap
          cd data
          cp bridge2ai_voice_project_data_dictionary.csv ../../.
          cd ../..
          ls
      
      - name: Generate reporschema
        run: |
          rm -r b2ai-redcap2rs
          cd bridge2ai-redcap
          touch protocol.yaml
          echo -e protocol_name: "b2ai-redcap2rs" >> protocol.yaml
          echo -e protocol_display_name: "Assessment Protocol" >> protocol.yaml
          echo -e protocol_description: "This protocol is for B2AI" >> protocol.yaml
          redcap_version: "${GITHUB_REF#refs/tags/} >> protocol.yaml
          cat protocol.yaml
          cp protocol.yaml ..
          ls


      

        

      


  